easy_admin:
    entities:
        Category:
            class: App\Domain\Category\Category
            controller: App\Ui\Admin\Controller\CategoryController
        Tag:
            class: App\Domain\Tag\Tag
            controller: App\Ui\Admin\Controller\TagController
        Post:
            class: App\Domain\Post\Post
            controller: App\Ui\Admin\Controller\PostController
