vich_uploader:
    db_driver: orm
    metadata:
        auto_detection: false
        directories:
            - {path: '%kernel.project_dir%/config/vich_uploader', namespace_prefix: 'App\Domain'}
    mappings:
        product_image:
            uri_prefix: '%app.path.product_images%'
            upload_destination: '%kernel.project_dir%/public/images/products'
