App\Domain\Post\Post:
    type: entity
    table: post
    id:
        id:
            type: integer
            generator:
                strategy: auto
    fields:
        title:
            type: string
        content:
            type: text
        createdAt:
            type: datetime
    manyToOne:
        category:
            targetEntity: App\Domain\Category\Category
            joinColumn:
                nullable: false
    manyToMany:
        tags:
            targetEntity: App\Domain\Tag\Tag
